# Generated by Django 3.2.13 on 2023-07-12 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
